config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'
  get 'customers/missing_email'
  get 'customers/alphabetized'
  resources :customers
  root 'customers#index'



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order(:full_name)
  end

  def missing_email
    @customers = Customer.all.where(email_address: '')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_choices.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Find Your Customer</h1>
    <div class="btn-group">
      <%= link_to 'All Customer', customers_index_path , :class => "btn btn-secondary"%>
      <%= link_to 'Order Customers by Alphabet', customers_alphabetized_path, :class => "btn btn-secondary" %>
      <%= link_to 'Show customers without email', customers_missing_email_path , :class => "btn btn-secondary"%>
    </div>
  </div>
</div>

app/views/customers/_customer.html.erb
<div class="jumbotron">
    <h1 class="display-4">All Customers</h1>
    <div class="card-group">
      <% @customers.each do |customer| %>
        <div class="card">
          <div class="card-body">
            <h3 class="card-title"><%= customer.full_name %></h3>
            <p class="card-text"><%= customer.phone_number %></p>
            <p class="card-text"><%= customer.email_address %></small></p>
          </div>
          <%= image_tag customer.image, :class => "card-img-top ", :alt => customer.full_name %>
        </div>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomRelationManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "customers/choices" %>
    <%= yield %>
    <%= render partial: "customers/customer" %>
  </body>
</html>